package View;

import Controller.NhanVienController;
import DAO.DataBaseConnection;
import DAO.NhanVienDAO;
import Model.NhanVien;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author asus
 */
public class QuanLiNhanVienJPane extends javax.swing.JPanel {
    private ArrayList<NhanVien> listNhanVien;
//    static int curr_MaNV;
    Date date = new Date();
    
    DefaultTableModel tblNhanVien;
    public QuanLiNhanVienJPane() {
        initComponents();
        NhanVienDAO nvDAO = new NhanVienDAO();
//        curr_MaNV = nvDAO.getCurrentMaNV();
//        Text_MaNhanVien.setText(Integer.toString(curr_MaNV));
        listNhanVien = nvDAO.getListNhanVien();
        tblNhanVien = (DefaultTableModel) Table_NhanVien.getModel();
        tblNhanVien.setColumnIdentifiers(new Object[]{"STT","Mã nhân viên", "Tên nhân viên", "CMND/CCCD", "Ngày sinh", 
            "Số điện thoại", "Giới tính", "Ngày vào làm", "Chức vụ"});
        showTable();
        Button_XoaNhanVien.setEnabled(false);
        Button_SuaNhanVien.setEnabled(false);
        Table_NhanVien.setShowHorizontalLines(true);
        Table_NhanVien.setDefaultEditor(Object.class, null);    
    }
    
    public void showTable(){
        int i = 1;
        listNhanVien = new NhanVienDAO().getListNhanVien();
        for(NhanVien nv : listNhanVien){
            tblNhanVien.addRow(new Object[]{i++, nv.getMaNV(), nv.getTenNV(), nv.getCCCD(), new SimpleDateFormat("dd-MM-yyyy").format(nv.getNgaySinh()),
                nv.getSDT(), nv.getGioiTinh(), new SimpleDateFormat("dd-MM-yyyy").format(nv.getNgayVaoLam()), nv.getChucVu()});
            
        }
    }
    public void updateTable(){
        tblNhanVien.setRowCount(0);
        this.showTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Text_MaNhanVien = new javax.swing.JTextField();
        Text_HoTen = new javax.swing.JTextField();
        Text_CCCD = new javax.swing.JTextField();
        Text_SDT = new javax.swing.JTextField();
        ComboBox_GioiTinh = new javax.swing.JComboBox<>();
        ComboBox_ChucVu = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        Button_ThemNhanVien = new javax.swing.JButton();
        Button_XoaNhanVien = new javax.swing.JButton();
        Button_SuaNhanVien = new javax.swing.JButton();
        Button_TimKiemNhanVien = new javax.swing.JButton();
        Button_InDSNV = new javax.swing.JButton();
        Button_LamMoi = new javax.swing.JButton();
        Button_TaoTK = new javax.swing.JButton();
        JDateChooser_NgaySinh = new com.toedter.calendar.JDateChooser();
        JDateChooser_NgayVaoLam = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_NhanVien = new javax.swing.JTable();

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CMND/CCCD");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ngày sinh");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Số điện thoại");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Giới tính");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ngày vào làm");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Chức vụ");

        Text_MaNhanVien.setEditable(false);
        Text_MaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_HoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_CCCD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ComboBox_GioiTinh.setMaximumRowCount(3);
        ComboBox_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        ComboBox_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếp tân", "Kế toán", "Quản lí" }));

        Button_ThemNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_ThemNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Add_Icon.png"))); // NOI18N
        Button_ThemNhanVien.setText("Thêm");
        Button_ThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ThemNhanVienActionPerformed(evt);
            }
        });

        Button_XoaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_XoaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Delete_Icon.png"))); // NOI18N
        Button_XoaNhanVien.setText("Xóa");
        Button_XoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_XoaNhanVienActionPerformed(evt);
            }
        });

        Button_SuaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_SuaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Fix_Icon.png"))); // NOI18N
        Button_SuaNhanVien.setText("Sửa");
        Button_SuaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SuaNhanVienActionPerformed(evt);
            }
        });

        Button_TimKiemNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_TimKiemNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Search_Icon.png"))); // NOI18N
        Button_TimKiemNhanVien.setText("Tìm kiếm");
        Button_TimKiemNhanVien.setMaximumSize(new java.awt.Dimension(115, 40));
        Button_TimKiemNhanVien.setMinimumSize(new java.awt.Dimension(115, 40));
        Button_TimKiemNhanVien.setPreferredSize(new java.awt.Dimension(115, 40));
        Button_TimKiemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TimKiemNhanVienActionPerformed(evt);
            }
        });

        Button_InDSNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_InDSNV.setText("In danh sách");
        Button_InDSNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_InDSNVActionPerformed(evt);
            }
        });

        Button_LamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_LamMoi.setText("Làm mới");
        Button_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LamMoiActionPerformed(evt);
            }
        });

        Button_TaoTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Button_TaoTK.setText("Tạo tài khoản");
        Button_TaoTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TaoTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_TimKiemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_InDSNV, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_TaoTK, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(Button_ThemNhanVien)
                .addGap(18, 18, 18)
                .addComponent(Button_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_SuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_XoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_XoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_SuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_TimKiemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_ThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_InDSNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Button_TaoTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JDateChooser_NgaySinh.setDateFormatString("dd-MM-yyyy");
        JDateChooser_NgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JDateChooser_NgayVaoLam.setDate(date);
        JDateChooser_NgayVaoLam.setDateFormatString("dd-MM-yyyy");
        JDateChooser_NgayVaoLam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JDateChooser_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JDateChooser_NgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Text_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Text_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Text_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(ComboBox_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(Text_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(JDateChooser_NgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(ComboBox_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(JDateChooser_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin nhân viên");

        Table_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên", "Họ tên", "CMND/CCCD", "Ngày sinh", "Số điện thoại", "Giới tính", "Ngày vào làm", "Chức vụ"
            }
        ));
        Table_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_NhanVien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(777, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ThemNhanVienActionPerformed
        if(new NhanVienController().KtraJTextNhanVien(Text_HoTen, Text_CCCD, JDateChooser_NgaySinh, Text_SDT, JDateChooser_NgayVaoLam)){
            NhanVien nv = new NhanVien();
    //        nv.setMaNV(Integer.parseInt(Text_MaNhanVien.getText()));
            nv.setTenNV(Text_HoTen.getText());
            nv.setCCCD(Text_CCCD.getText());
            nv.setNgaySinh(JDateChooser_NgaySinh.getDate());
            nv.setSDT(Text_SDT.getText());
            nv.setGioiTinh(ComboBox_GioiTinh.getSelectedItem().toString());
            nv.setNgayVaoLam(JDateChooser_NgayVaoLam.getDate());
            nv.setChucVu(ComboBox_ChucVu.getSelectedItem().toString());
              if(new NhanVienDAO().ThemNhanVien(nv)){
                JOptionPane.showMessageDialog(this, "Thêm thành công.");
    //            NhanVienDAO nvDAO = new NhanVienDAO();
    //            curr_MaNV = nvDAO.getCurrentMaNV();
    //            listNhanVien = nvDAO.getListNhanVien();                        
    //            showResult();
    //            System.out.println(JDateChooser_NgaySinh.getDate());
    //            System.out.println(JDateChooser_NgayVaoLam.getDate());             
                resetJTextNhanVien();
                updateTable();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại.");
            }
        }
    }//GEN-LAST:event_Button_ThemNhanVienActionPerformed
    
    private void Button_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LamMoiActionPerformed
        resetJTextNhanVien();
        Button_ThemNhanVien.setEnabled(true);
        Button_XoaNhanVien.setEnabled(false);
        Button_SuaNhanVien.setEnabled(false);
        updateTable();
    }//GEN-LAST:event_Button_LamMoiActionPerformed

    private void Button_XoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_XoaNhanVienActionPerformed
        StringBuilder sb = new StringBuilder();
        if(Text_MaNhanVien.getText().equals("")){
            Text_MaNhanVien.setBackground(Color.red);
        }else{
            Text_MaNhanVien.setBackground(Color.white);
        }
        
        if(sb.length() > 0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá thông tin nhân viên không?", "Xóa nhân viên.", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.NO_OPTION){
            return;
        }
        if(new NhanVienDAO().CheckTKNV(Integer.parseInt(Text_MaNhanVien.getText().toString()))){
            if(!new NhanVienDAO().XoaTK(Integer.parseInt(Text_MaNhanVien.getText().toString()))){
            JOptionPane.showMessageDialog(this, "Lỗi. Không thể xóa tài khoản.");
            return;
            }
        }
        if(new NhanVienDAO().XoaNhanVien(Integer.parseInt(Text_MaNhanVien.getText().toString()))){
            JOptionPane.showMessageDialog(this, "Xóa thành công."); 
            updateTable();
            resetJTextNhanVien();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
//        NhanVienDAO nvDAO = new NhanVienDAO();
//        listNhanVien = nvDAO.getListNhanVien();
//        for(NhanVien nv : listNhanVien){
//            if(nv.getMaNV() ==  Integer.parseInt(Text_MaNhanVien.getText())){
//                nvDAO.XoaNhanVien(nv);
//                JOptionPane.showMessageDialog(this, "Xóa thành công.");
//                break;
//            } else { JOptionPane.showMessageDialog(this, "Xóa thất bại");}
//        }
        updateTable();
        resetJTextNhanVien();
    }//GEN-LAST:event_Button_XoaNhanVienActionPerformed
    
    public NhanVien returnNhanVien(int index){       
        try {
            int MaNV = Integer.parseInt(tblNhanVien.getValueAt(index, 1).toString());
            String HoTen = tblNhanVien.getValueAt(index, 2).toString();
            String CCCD = tblNhanVien.getValueAt(index, 3).toString();
            Date NgaySinh = new SimpleDateFormat("dd-MM-yyyy").parse(tblNhanVien.getValueAt(index, 4).toString());
            String SDT = tblNhanVien.getValueAt(index, 5).toString();
            String GioiTinh = tblNhanVien.getValueAt(index, 6).toString();
            Date NgayVaoLam = new SimpleDateFormat("dd-MM-yyyy").parse(tblNhanVien.getValueAt(index, 7).toString());
            String ChucVu = tblNhanVien.getValueAt(index, 8).toString();
            return new NhanVien(MaNV, HoTen, CCCD, NgaySinh, SDT, GioiTinh, NgayVaoLam, ChucVu);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
    
    private void Button_SuaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SuaNhanVienActionPerformed
        if(new NhanVienController().KtraJTextNhanVien(Text_HoTen, Text_CCCD, JDateChooser_NgaySinh, Text_SDT, JDateChooser_NgayVaoLam)){
            int indexTB = Table_NhanVien.getSelectedRow();
            int MaNV = Integer.parseInt(Text_MaNhanVien.getText());
            String Hoten = Text_HoTen.getText();
            String CCCD = Text_CCCD.getText();
            Date NgaySinh = JDateChooser_NgaySinh.getDate();
            String SDT = Text_SDT.getText();
            String GioiTinh = ComboBox_GioiTinh.getSelectedItem().toString();
            Date NgayVaoLam = JDateChooser_NgayVaoLam.getDate();
            String ChucVu = ComboBox_ChucVu.getSelectedItem().toString();
            NhanVien nv = new NhanVien(MaNV, Hoten, CCCD, NgaySinh, SDT, GioiTinh, NgayVaoLam, ChucVu);
            int ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa dữ liệu?", "Sửa dữ liệu", JOptionPane.YES_NO_OPTION);
            if(ret == JOptionPane.YES_OPTION){
                if(new NhanVienDAO().SuaNhanVien(nv)){
                    if(indexTB < tblNhanVien.getRowCount() && indexTB >= 0){
                        tblNhanVien.setValueAt(Text_HoTen.getText(), indexTB, 2);
                        tblNhanVien.setValueAt(Text_CCCD.getText(), indexTB, 3);
                        tblNhanVien.setValueAt( new SimpleDateFormat("dd-MM-yyyy").format(JDateChooser_NgaySinh.getDate()), indexTB, 4);
                        tblNhanVien.setValueAt(Text_SDT.getText(), indexTB, 5);
                        tblNhanVien.setValueAt(ComboBox_GioiTinh.getSelectedItem(), indexTB, 6);
                        tblNhanVien.setValueAt(new SimpleDateFormat("dd-MM-yyyy").format(JDateChooser_NgayVaoLam.getDate()), indexTB, 7);
                        tblNhanVien.setValueAt(ComboBox_ChucVu.getSelectedItem(), indexTB, 8);
                        JOptionPane.showMessageDialog(this, "Sửa thành công.");
                        resetJTextNhanVien();
                    } else {
                        JOptionPane.showMessageDialog(this, "Sửa thất bại.");
                    }
                }
            }
           
        }
    }//GEN-LAST:event_Button_SuaNhanVienActionPerformed

    private void viewReport(String fileName, HashMap para) {
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(fileName, para, DataBaseConnection.getConnection());
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    private void Button_InDSNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_InDSNVActionPerformed
        viewReport("src\\Reports\\DanhSachNhanVien.jasper", null);
    }//GEN-LAST:event_Button_InDSNVActionPerformed

    private void Table_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_NhanVienMouseClicked
        ListSelectionModel listTable_NhanVien = Table_NhanVien.getSelectionModel();
        listTable_NhanVien.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        Button_ThemNhanVien.setEnabled(false);
        Button_XoaNhanVien.setEnabled(true);
        Button_SuaNhanVien.setEnabled(true);
        
        int indexTB = Table_NhanVien.getSelectedRow();
        if (indexTB < tblNhanVien.getRowCount() && indexTB >= 0){
            Text_MaNhanVien.setText(tblNhanVien.getValueAt(indexTB, 1).toString());
            Text_HoTen.setText(tblNhanVien.getValueAt(indexTB, 2).toString());
            Text_CCCD.setText(tblNhanVien.getValueAt(indexTB, 3).toString());
            try {
                JDateChooser_NgaySinh.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(tblNhanVien.getValueAt(indexTB, 4).toString()));
            } catch (Exception e) {
                e.printStackTrace();
            }
            Text_SDT.setText(tblNhanVien.getValueAt(indexTB, 5).toString());
            ComboBox_GioiTinh.setSelectedItem(tblNhanVien.getValueAt(indexTB, 6));
            try {
                JDateChooser_NgayVaoLam.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(tblNhanVien.getValueAt(indexTB, 7).toString()));
            } catch (Exception e) {
               e.printStackTrace();
            }
            ComboBox_ChucVu.setSelectedItem(tblNhanVien.getValueAt(indexTB, 8));
        }
    }//GEN-LAST:event_Table_NhanVienMouseClicked

    public void showKetQuaTimKiemNV(NhanVien KQTKNhanVien){
        listNhanVien = new NhanVienDAO().TimKiemNhanVien(KQTKNhanVien);
        tblNhanVien.setRowCount(0);
        int i = 1;
        for(NhanVien data : listNhanVien){
            tblNhanVien.addRow(new Object[]{i++, data.getMaNV(), data.getTenNV(), data.getCCCD(), new SimpleDateFormat("dd-MM-yyyy").format(data.getNgaySinh()),
                data.getSDT(), data.getGioiTinh(), new SimpleDateFormat("dd-MM-yyyy").format(data.getNgayVaoLam()), data.getChucVu()});
        }
        if(listNhanVien.size() <= 0){
             JOptionPane.showMessageDialog(this,"Không tìm thấy thông tin nhân viên. Vui lòng kiểm tra lại!");
        }
    }
    
    private void Button_TimKiemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TimKiemNhanVienActionPerformed
        NhanVien nv = new NhanVien();
        nv.setTenNV(Text_HoTen.getText());
        nv.setCCCD(Text_CCCD.getText());
        nv.setSDT(Text_SDT.getText());
//        nv.setChucVu(ComboBox_ChucVu.getSelectedItem().toString());
        showKetQuaTimKiemNV(nv);
    }//GEN-LAST:event_Button_TimKiemNhanVienActionPerformed

    private void Button_TaoTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TaoTKActionPerformed
        new TaoTaiKhoanJFrame();
    }//GEN-LAST:event_Button_TaoTKActionPerformed
    public void resetJTextNhanVien(){
//        Text_MaNhanVien.setText(Integer.toString(curr_MaNV));
        Text_MaNhanVien.setText("");
        Text_HoTen.setText("");
        Text_CCCD.setText("");
        JDateChooser_NgaySinh.setDate(null);
        Text_SDT.setText("");
        ComboBox_GioiTinh.setSelectedItem("Nam");
        JDateChooser_NgayVaoLam.setDate(date);
        ComboBox_GioiTinh.setSelectedItem("Tiếp tân");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_InDSNV;
    private javax.swing.JButton Button_LamMoi;
    private javax.swing.JButton Button_SuaNhanVien;
    private javax.swing.JButton Button_TaoTK;
    private javax.swing.JButton Button_ThemNhanVien;
    private javax.swing.JButton Button_TimKiemNhanVien;
    private javax.swing.JButton Button_XoaNhanVien;
    private javax.swing.JComboBox<String> ComboBox_ChucVu;
    private javax.swing.JComboBox<String> ComboBox_GioiTinh;
    private com.toedter.calendar.JDateChooser JDateChooser_NgaySinh;
    private com.toedter.calendar.JDateChooser JDateChooser_NgayVaoLam;
    private javax.swing.JTable Table_NhanVien;
    private javax.swing.JTextField Text_CCCD;
    private javax.swing.JTextField Text_HoTen;
    private javax.swing.JTextField Text_MaNhanVien;
    private javax.swing.JTextField Text_SDT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
