/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ThamSoController;
import DAO.DataBaseConnection;
import Model.ThamSo;
import DAO.ThamSoDAO;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author asus
 */
public class QuanLiThamSoJPane extends javax.swing.JPanel {
    private ArrayList<ThamSo> listThamSo;
    DefaultTableModel tblThamSo;
//    static int curr_MaKH;
    public QuanLiThamSoJPane() {       
        initComponents();
        ThamSoDAO tsDAO = new ThamSoDAO();
//        curr_MaKH =khDAO.getCurrentMaKH();
        //Text_MaKhachHang.setText(Integer.toString(curr_MaKH));
        listThamSo = tsDAO.getListThamSo();
        tblThamSo = (DefaultTableModel) Table_ThamSo.getModel();
        tblThamSo.setColumnIdentifiers(new Object[]{"STT", "Mã tham số", "Tên tham số", "Giá Trị"});
        showTable();
        showComboData();
        Button_SuaThamSo.setEnabled(false);
        Table_ThamSo.setShowHorizontalLines(true);
        Table_ThamSo.setDefaultEditor(Object.class, null);
    }
    
    public void showComboData(){
        listThamSo = new ThamSoDAO().getListThamSo();
        for(ThamSo ts : listThamSo){
            ComboBox_ThamSo.addItem(ts.getTenTS());
        }
    }
    
    public void showTable(){
        int i = 1;
        listThamSo = new ThamSoDAO().getListThamSo();
        for(ThamSo ts : listThamSo){
            tblThamSo.addRow(new Object[]{i++, ts.getMaTS(), ts.getTenTS(), ts.getGiaTri()});
        }
    }
    public void updateTable(){
        tblThamSo.setRowCount(0);
        this.showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Text_MaThamSo = new javax.swing.JTextField();
        Text_GiaTri = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ComboBox_ThamSo = new javax.swing.JComboBox<>();
        Button_SuaThamSo = new javax.swing.JButton();
        Button_LamMoi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_ThamSo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã tham số");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Giá trị");

        Text_MaThamSo.setEditable(false);
        Text_MaThamSo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_GiaTri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_GiaTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_GiaTriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tên tham số");

        ComboBox_ThamSo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboBox_ThamSo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Khác"}));
        ComboBox_ThamSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBox_ThamSoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ComboBox_ThamSoMouseEntered(evt);
            }
        });
        ComboBox_ThamSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_ThamSoActionPerformed(evt);
            }
        });

        Button_SuaThamSo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_SuaThamSo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Fix_Icon.png"))); // NOI18N
        Button_SuaThamSo.setText("Sửa");
        Button_SuaThamSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SuaThamSoActionPerformed(evt);
            }
        });

        Button_LamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_LamMoi.setText("Làm mới");
        Button_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(Text_GiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Text_MaThamSo)
                            .addComponent(ComboBox_ThamSo, 0, 273, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(Button_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_SuaThamSo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Text_MaThamSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_SuaThamSo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ComboBox_ThamSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(Text_GiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Table_ThamSo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã tham số", "Tham số", "Giá trị"
            }
        ));
        Table_ThamSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ThamSoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_ThamSo);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Thay đổi quy định");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void Table_ThamSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ThamSoMouseClicked
        ListSelectionModel listTable_KhachHang = Table_ThamSo.getSelectionModel();
        listTable_KhachHang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//        Button_ThemKhachHang.setEnabled(false);
        Button_SuaThamSo.setEnabled(true);
//        Button_XoaKhachHang.setEnabled(true);
        int indexTB = Table_ThamSo.getSelectedRow();
        if (indexTB < tblThamSo.getRowCount() && indexTB >= 0){
            Text_GiaTri.setEditable(true);
            Text_MaThamSo.setText(tblThamSo.getValueAt(indexTB, 1).toString());
//            TextThamSo.setText(tblThamSo.getValueAt(indexTB, 2).toString());
//            Text_CCCD.setText(tblThamSo.getValueAt(indexTB, 3).toString());
            ComboBox_ThamSo.setSelectedItem(tblThamSo.getValueAt(indexTB, 2));
            Text_GiaTri.setText(tblThamSo.getValueAt(indexTB, 3).toString());
        }
    }//GEN-LAST:event_Table_ThamSoMouseClicked

//    public KhachHang returnKhachHang(int index){       
//        int MaKH = Integer.parseInt(tblKhachHang.getValueAt(index, 1).toString());
//        String HoTen = tblKhachHang.getValueAt(index, 2).toString();
//        String CCCD = tblKhachHang.getValueAt(index, 3).toString();
//        String GioiTinh = tblKhachHang.getValueAt(index, 4).toString();
//        String SDT = tblKhachHang.getValueAt(index, 5).toString();      
//        return new KhachHang(MaKH,HoTen,CCCD,GioiTinh,SDT);
//    }
    
    private void Button_SuaThamSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SuaThamSoActionPerformed
        if(new ThamSoController().KtraJtextThamSo(Text_GiaTri)){
            int indexTB = Table_ThamSo.getSelectedRow();
            String MaTS = Text_MaThamSo.getText().toString();
            String ThamSo = ComboBox_ThamSo.getSelectedItem().toString();
            String GiaTri = Text_GiaTri.getText();
            ThamSo ts = new ThamSo(MaTS, ThamSo, GiaTri);
            int ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa dữ liệu?", "Sửa dữ liệu", JOptionPane.YES_NO_OPTION);
            if(ret == JOptionPane.YES_OPTION){
                if(new ThamSoDAO().SuaThamSo(ts)){
                    if(indexTB < tblThamSo.getRowCount() && indexTB >= 0){
                        tblThamSo.setValueAt(Text_GiaTri.getText(), indexTB, 3);
//                        tblThamSo.setValueAt(Text_CCCD.getText(), indexTB, 3);
//                        tblThamSo.setValueAt(ComboBox_GioiTinh.getSelectedItem(), indexTB, 4);
//                        tblThamSo.setValueAt(Text_SDT.getText(), indexTB, 5);
                        JOptionPane.showMessageDialog(this, "Sửa thành công.");  
                        clearJTextThamSo();
                    } else {
                        JOptionPane.showMessageDialog(this, "Sửa thất bại.");
                    }
                }
            }
        }
    }//GEN-LAST:event_Button_SuaThamSoActionPerformed

    private void Button_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LamMoiActionPerformed
//        Button_ThemKhachHang.setEnabled(true);
//        Button_XoaKhachHang.setEnabled(false);
        Button_SuaThamSo.setEnabled(false);
        clearJTextThamSo();
        updateTable();
    }//GEN-LAST:event_Button_LamMoiActionPerformed
    
    private void ComboBox_ThamSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_ThamSoActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String)ComboBox_ThamSo.getSelectedItem();
        listThamSo = new ThamSoDAO().getListThamSo();
        for (int row = 0; row < Table_ThamSo.getRowCount(); row++) {
            if (Table_ThamSo.getValueAt(row, 2).equals(selectedItem)){
                String GiaTri = Table_ThamSo.getValueAt(row, 3).toString();
                String MaThamSo = Table_ThamSo.getValueAt(row, 1).toString();
                Text_GiaTri.setText(GiaTri);
                Text_MaThamSo.setText(MaThamSo);
            } 
            else if (selectedItem.equals("Khác")){
                Text_GiaTri.setText("");
                Text_MaThamSo.setText("");
            }
        }
    }//GEN-LAST:event_ComboBox_ThamSoActionPerformed

    private void ComboBox_ThamSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_ThamSoMouseClicked
        // TODO add your handling code here:
        Text_GiaTri.setEditable(false);
        Button_SuaThamSo.setEnabled(false);
    }//GEN-LAST:event_ComboBox_ThamSoMouseClicked

    private void Text_GiaTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_GiaTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_GiaTriActionPerformed

    private void ComboBox_ThamSoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_ThamSoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_ThamSoMouseEntered
    
    
    public void clearJTextThamSo(){
//        Text_MaKhachHang.setText(Integer.toString(curr_MaKH));
        Text_GiaTri.setText("");
        Text_MaThamSo.setText("");
        ComboBox_ThamSo.setSelectedItem("Khác");
    }
//    public void showResult(){
//        //int i = 1;
//        KhachHang kh = listKhachHang.get(listKhachHang.size() - 1);
//        tblKhachHang.addRow(new Object[]{ kh.getMaKH(), kh.getTenKH(), kh.getCCCD(), kh.getGioiTinh(), kh.getSDT()});
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_LamMoi;
    private javax.swing.JButton Button_SuaThamSo;
    public javax.swing.JComboBox<String> ComboBox_ThamSo;
    private javax.swing.JTable Table_ThamSo;
    private javax.swing.JTextField Text_GiaTri;
    private javax.swing.JTextField Text_MaThamSo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
