/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DataBaseConnection;
import Model.KhachHang;
import com.toedter.calendar.JMonthChooser;
import com.toedter.calendar.JYearChooser;
import java.awt.Button;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.InputStream;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
import java.util.Map;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;



/**
 *
 * @author asus
 */
public class ThongKeJPane extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeJPane
     */
    DefaultTableModel tblHoaDon;
    public ThongKeJPane() {
        initComponents();
        tblHoaDon = (DefaultTableModel) Table_HoaDon.getModel();
        showTable();
        Table_HoaDon.setShowHorizontalLines(true);
        Table_HoaDon.setDefaultEditor(Object.class, null);            
    }

    public void showTable(){
        tblHoaDon.setRowCount(0);
        Connection con = DataBaseConnection.getConnection();
        int MaThanhToan;
        int MaNV;
        int MaKH;
        String MaPhg;
        String TenNV;
        String TenKH;
        java.sql.Date NgayLap;
        String sql = "SELECT T.MATHANHTOAN, T.MANV, T.NGAYLAP,  P.MAKH, C.MAPHG, N.TENNV, K.TENKH\n" +
                    "FROM THANHTOAN T\n" +
                    "INNER JOIN \n" +
                        "PHIEUDATPHONG P\n" +
                    "ON T.MADATPHONG = P.MADATPHONG\n" +
                    "INNER JOIN\n" +
                        "CHITIETDATPHONG C\n" +
                    "ON P.MADATPHONG = C.MADATPHONG\n" +
                    "INNER JOIN\n" + 
                        "NHANVIEN N\n" +
                    "ON N.MANV = T.MANV\n" +   
                    "INNER JOIN\n" + 
                        "KHACHHANG K\n" +
                    "ON P.MAKH = K.MAKH";
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            int i = 1;
            while(rs.next()){
                MaThanhToan = rs.getInt("MATHANHTOAN");
                MaNV = rs.getInt("MANV");
                MaKH = rs.getInt("MAKH");
                MaPhg = rs.getString("MAPHG");
                TenNV = rs.getString("TENNV");
                TenKH = rs.getString("TENKH");
                NgayLap = rs.getDate("NGAYLAP");
                if (MaThanhToan != 0)
                    tblHoaDon.addRow(new Object[]{i++, MaThanhToan, NgayLap, MaNV, TenNV, MaKH, TenKH, MaPhg});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_TKSLDatDV = new javax.swing.JButton();
        Button_TKDoanhThuThang = new javax.swing.JButton();
        Button_HoaDonThanhToan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_HoaDon = new javax.swing.JTable();

        jPanel1.setToolTipText("");

        Button_TKSLDatDV.setBackground(new java.awt.Color(255, 255, 204));
        Button_TKSLDatDV.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Button_TKSLDatDV.setForeground(new java.awt.Color(102, 0, 102));
        Button_TKSLDatDV.setText("Thống kê doanh thu theo loại dịch vụ");
        Button_TKSLDatDV.setActionCommand("Thống kê doanh thu theo dịch vụ");
        Button_TKSLDatDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_TKSLDatDVMouseClicked(evt);
            }
        });
        Button_TKSLDatDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TKSLDatDVActionPerformed(evt);
            }
        });

        Button_TKDoanhThuThang.setBackground(new java.awt.Color(255, 255, 204));
        Button_TKDoanhThuThang.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Button_TKDoanhThuThang.setForeground(new java.awt.Color(0, 102, 102));
        Button_TKDoanhThuThang.setText("Thống kê doanh thu theo loại phòng");
        Button_TKDoanhThuThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TKDoanhThuThangActionPerformed(evt);
            }
        });

        Button_HoaDonThanhToan.setBackground(new java.awt.Color(255, 255, 204));
        Button_HoaDonThanhToan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Button_HoaDonThanhToan.setForeground(new java.awt.Color(102, 102, 0));
        Button_HoaDonThanhToan.setText("Hóa đơn thanh toán");
        Button_HoaDonThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HoaDonThanhToanActionPerformed(evt);
            }
        });

        Table_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã thanh toán", "Ngày lập", "Mã nhân viên", "Tên nhân viên", "Mã khách hàng", "Tên khách hàng", "Mã Phòng"
            }
        ));
        jScrollPane1.setViewportView(Table_HoaDon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_HoaDonThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_TKSLDatDV, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                            .addComponent(Button_TKDoanhThuThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(610, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Button_TKSLDatDV, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_TKDoanhThuThang, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_HoaDonThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void Button_HoaDonThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HoaDonThanhToanActionPerformed
        BigDecimal matt;
        HashMap para = new HashMap();
        try{
            String str = JOptionPane.showInputDialog(null, "Nhập vào mã thanh toán (Số nguyên)");
            matt = new BigDecimal(str);
            para.put("matt", matt);
            viewReport("src\\Reports\\HoaDonThanhToan_1.jasper", para);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Bạn phải nhập vào số nguyên!");
        }
    }//GEN-LAST:event_Button_HoaDonThanhToanActionPerformed

    private void Button_TKDoanhThuThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TKDoanhThuThangActionPerformed
        JPanel pan= new JPanel();
        pan.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx= 0;
        gbc.gridy= 0;
        JLabel Label_Thang= new JLabel("Chọn tháng ");
        pan.add(Label_Thang, gbc);
        gbc.gridx= 1;
        gbc.gridy= 0;
        JMonthChooser Thang = new JMonthChooser();
        pan.add(Thang, gbc);
        gbc.gridx= 0;
        gbc.gridy= 1;
        JLabel Label_Nam= new JLabel("Chọn năm ");
        pan.add(Label_Nam, gbc);
        gbc.gridx= 1;
        gbc.gridy= 1;
        JYearChooser Nam = new JYearChooser();
        pan.add(Nam, gbc);
        gbc.gridx= 0;
        gbc.gridy= 2;
        gbc.gridwidth = 2;
        Button bt_OK = new Button("OK");
        pan.add(bt_OK, gbc);
        JDialog jd= new JDialog();
        jd.setTitle("Lựa chọn");
        jd.setSize(200, 150);
        jd.add(pan);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        bt_OK.setActionCommand("OK");
        bt_OK.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                if ("OK".equals(e.getActionCommand())){
                    BigDecimal thang = new BigDecimal(Thang.getMonth() + 1);
                    BigDecimal nam = new BigDecimal(Nam.getYear());
                    HashMap para = new HashMap();
                    para.put("thang", thang);
                    para.put("nam", nam);

                    viewReport("src\\Reports\\DoanhThuLoaiPhong.jasper",para);
                    jd.setVisible(false);
                }
            }
        });
    }//GEN-LAST:event_Button_TKDoanhThuThangActionPerformed

    private void Button_TKSLDatDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TKSLDatDVActionPerformed
        JPanel pan= new JPanel();
        pan.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx= 0;
        gbc.gridy= 0;
        JLabel Label_Thang= new JLabel("Chọn tháng ");
        pan.add(Label_Thang, gbc);
        gbc.gridx= 1;
        gbc.gridy= 0;
        JMonthChooser Thang = new JMonthChooser();
        pan.add(Thang, gbc);
        gbc.gridx= 0;
        gbc.gridy= 1;
        JLabel Label_Nam= new JLabel("Chọn năm ");
        pan.add(Label_Nam, gbc);
        gbc.gridx= 1;
        gbc.gridy= 1;
        JYearChooser Nam = new JYearChooser();
        pan.add(Nam, gbc);
        gbc.gridx= 0;
        gbc.gridy= 2;
        gbc.gridwidth = 2;
        Button bt_OK = new Button("OK");
        pan.add(bt_OK, gbc);
        JDialog jd= new JDialog();
        jd.setTitle("Lựa chọn");
        jd.setSize(200, 150);
        jd.add(pan);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        bt_OK.setActionCommand("OK");
        bt_OK.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                if ("OK".equals(e.getActionCommand())){
                    BigDecimal thang = new BigDecimal(Thang.getMonth() + 1);
                    BigDecimal nam = new BigDecimal(Nam.getYear());
                    HashMap para = new HashMap();
                    para.put("thang", thang);
                    para.put("nam", nam);
                    viewReport("src\\Reports\\DoanhThuLoaiDV.jasper",para);
                    jd.setVisible(false);
                }
            }
        });

    }//GEN-LAST:event_Button_TKSLDatDVActionPerformed

    private void Button_TKSLDatDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_TKSLDatDVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_TKSLDatDVMouseClicked


    public void viewReport(String fileName, HashMap para){
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(fileName, para, DataBaseConnection.getConnection());
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setVisible(true);
        } catch (Exception ex) {
           System.out.println("Lỗi khi tạo báo cáo: " + ex.getMessage());
        }
        
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_HoaDonThanhToan;
    private javax.swing.JButton Button_TKDoanhThuThang;
    private javax.swing.JButton Button_TKSLDatDV;
    private javax.swing.JTable Table_HoaDon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
